/*
 * This file is generated by jOOQ.
*/
package com.bai.system.login.jooq.tables;


import com.bai.system.login.jooq.Indexes;
import com.bai.system.login.jooq.Keys;
import com.bai.system.login.jooq.System;
import com.bai.system.login.jooq.tables.records.LanguageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 国际化语言表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language extends TableImpl<LanguageRecord> {

    private static final long serialVersionUID = -1901684676;

    /**
     * The reference instance of <code>system.language</code>
     */
    public static final Language LANGUAGE = new Language();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LanguageRecord> getRecordType() {
        return LanguageRecord.class;
    }

    /**
     * The column <code>system.language.language_id</code>. 语言Id
     */
    public final TableField<LanguageRecord, String> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "语言Id");

    /**
     * The column <code>system.language.language_code</code>. 语言编码
     */
    public final TableField<LanguageRecord, String> LANGUAGE_CODE = createField("language_code", org.jooq.impl.SQLDataType.VARCHAR(255), this, "语言编码");

    /**
     * The column <code>system.language.zh_cn</code>. 中文语言
     */
    public final TableField<LanguageRecord, String> ZH_CN = createField("zh_cn", org.jooq.impl.SQLDataType.VARCHAR(255), this, "中文语言");

    /**
     * The column <code>system.language.en_us</code>. 英文语言
     */
    public final TableField<LanguageRecord, String> EN_US = createField("en_us", org.jooq.impl.SQLDataType.VARCHAR(255), this, "英文语言");

    /**
     * Create a <code>system.language</code> table reference
     */
    public Language() {
        this(DSL.name("language"), null);
    }

    /**
     * Create an aliased <code>system.language</code> table reference
     */
    public Language(String alias) {
        this(DSL.name(alias), LANGUAGE);
    }

    /**
     * Create an aliased <code>system.language</code> table reference
     */
    public Language(Name alias) {
        this(alias, LANGUAGE);
    }

    private Language(Name alias, Table<LanguageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Language(Name alias, Table<LanguageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "国际化语言表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return System.SYSTEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LANGUAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LanguageRecord> getPrimaryKey() {
        return Keys.KEY_LANGUAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LanguageRecord>> getKeys() {
        return Arrays.<UniqueKey<LanguageRecord>>asList(Keys.KEY_LANGUAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Language as(String alias) {
        return new Language(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Language as(Name alias) {
        return new Language(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Language rename(String name) {
        return new Language(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Language rename(Name name) {
        return new Language(name, null);
    }
}
