/*
 * This file is generated by jOOQ.
*/
package com.bai.system.login.jooq;


import com.bai.system.login.jooq.tables.Language;
import com.bai.system.login.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class System extends SchemaImpl {

    private static final long serialVersionUID = 1556386710;

    /**
     * The reference instance of <code>system</code>
     */
    public static final System SYSTEM = new System();

    /**
     * 国际化语言表
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>system.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private System() {
        super("system", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Language.LANGUAGE,
            User.USER);
    }
}
