/*
 * This file is generated by jOOQ.
*/
package com.bai.system.login.jooq;


import com.bai.system.login.jooq.tables.Language;
import com.bai.system.login.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in system
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 国际化语言表
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>system.user</code>.
     */
    public static final User USER = User.USER;
}
