spring:
  datasource:
    url: jdbc:mysql://system_mysql:3306/@spring.application.name@?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 898392913
    initial-size: 5
    max-active: 5
