/*
 * This file is generated by jOOQ.
*/
package com.bai.system.login.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1961594679;

    private String        userId;
    private String        userName;
    private String        password;
    private String        createdUserId;
    private LocalDateTime createdDate;
    private String        updatedUserId;
    private LocalDateTime updatedDate;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.password = value.password;
        this.createdUserId = value.createdUserId;
        this.createdDate = value.createdDate;
        this.updatedUserId = value.updatedUserId;
        this.updatedDate = value.updatedDate;
    }

    public User(
        String        userId,
        String        userName,
        String        password,
        String        createdUserId,
        LocalDateTime createdDate,
        String        updatedUserId,
        LocalDateTime updatedDate
    ) {
        this.userId = userId;
        this.userName = userName;
        this.password = password;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
        this.updatedUserId = updatedUserId;
        this.updatedDate = updatedDate;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCreatedUserId() {
        return this.createdUserId;
    }

    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public String getUpdatedUserId() {
        return this.updatedUserId;
    }

    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    public LocalDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(LocalDateTime updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(createdUserId);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updatedUserId);
        sb.append(", ").append(updatedDate);

        sb.append(")");
        return sb.toString();
    }
}
