/*
 * This file is generated by jOOQ.
*/
package com.bai.system.login.jooq.tables.records;


import com.bai.system.login.jooq.tables.User;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record7<String, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -1619765234;

    /**
     * Setter for <code>system.user.user_id</code>. 用户ID
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>system.user.user_id</code>. 用户ID
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>system.user.user_name</code>. 用户名称
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>system.user.user_name</code>. 用户名称
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>system.user.password</code>. 用户密码
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>system.user.password</code>. 用户密码
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>system.user.created_user_id</code>. 创建用户Id
     */
    public void setCreatedUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>system.user.created_user_id</code>. 创建用户Id
     */
    public String getCreatedUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>system.user.created_date</code>. 创建用户时间
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>system.user.created_date</code>. 创建用户时间
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>system.user.updated_user_id</code>. 修改用户Id
     */
    public void setUpdatedUserId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>system.user.updated_user_id</code>. 修改用户Id
     */
    public String getUpdatedUserId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>system.user.updated_date</code>. 修改用户时间
     */
    public void setUpdatedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>system.user.updated_date</code>. 修改用户时间
     */
    public LocalDateTime getUpdatedDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return User.USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return User.USER.CREATED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return User.USER.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return User.USER.UPDATED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return User.USER.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUpdatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(String value) {
        setCreatedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(String value) {
        setUpdatedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(LocalDateTime value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(String value1, String value2, String value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String userId, String userName, String password, String createdUserId, LocalDateTime createdDate, String updatedUserId, LocalDateTime updatedDate) {
        super(User.USER);

        set(0, userId);
        set(1, userName);
        set(2, password);
        set(3, createdUserId);
        set(4, createdDate);
        set(5, updatedUserId);
        set(6, updatedDate);
    }
}
